esphome:
  name: esp32-ble-1
  friendly_name: esp32-ble-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "---snip----"

ota:
  password: "---snip----"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Ble-1 Fallback Hotspot"
    password: "---snip----"

captive_portal:
    

globals:
  - id: ipad_state
    type: bool
    restore_value: no
    initial_value: "false"

# Enable components
external_components:
  - source: github://dmamontov/esphome-blekeyboard

ble_keyboard:
  id: my_ble_keyboard
  name: "MyBleKeyboard"
  manufacturer_id: "Apple"
  reconnect: true
  buttons: false

switch:
  - platform: template
    name: "Screen iPad"
    icon: mdi:power
    lambda: |-
      if (id(ipad_state)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
        - lambda: |-
            id(ipad_state) = true;
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 1000
            keys:
              - 0x20
              - 0x20
        - ble_keyboard.press:
            id: my_ble_keyboard 
            code: 0x20

          
    turn_off_action:
        - lambda: |-
            id(ipad_state) = false;
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 100
            keys:
              - 0x83
              - 0x80
              - "q"
button:
  - platform: restart
    entity_category: "config"
    name: "Restart"

  - platform: template
    name: "Lock an iPad"
    id: lock_an_ipad
    icon: "mdi:lock"
    on_press:
      then:
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 100
            keys:
              - 0x83
              - 0x80
              - "q"

  - platform: template
    name: "unlock an iPad"
    id: unlock_an_ipad
    icon: "mdi:lock"
    on_press:
      then:
        - ble_keyboard.combination:
            id: my_ble_keyboard
            delay: 1000
            keys:
              - 0x20
              - 0x20
        - ble_keyboard.press:
            id: my_ble_keyboard 
            code: 0x20

  - platform: template
    name: "Start advertising"
    id: start_advertising
    icon: "mdi:play"
    on_press:
      then:
        - ble_keyboard.start: my_ble_keyboard

  - platform: template
    name: "Stop advertising"
    id: stop_advertising
    icon: "mdi:stop"
    on_press:
      then:
        - ble_keyboard.stop: my_ble_keyboard
